### ISSUE TITLE
Division by zero fault on clip with unknown FPS

### ISSUE THREAD

**Issue by sekrit-twc** [HomeOfVapourSynthEvolution/VapourSynth-TDeintMod#7]
http://www.vapoursynth.com/doc/api/vapoursynth.h.html#vsvideoinfo informs the programmer that fpsNum and fpsDen can be zero in the case of VFR input. When using TDeintMod in double rate mode, it attempts to do a division on the fraction 0/0, causing a SIGFPE. When the framerate is unknown, the plugin should set the output framerate as also unknown.

**Comment by HolyWu** [comment]
Thanks for the report.

**Comment by HolyWu** [comment]
Out of curiosity, how do we get a clip that will be reported as unknown FPS in VapourSynth? I tried to load a VFR mp4/mkv file by FFMS2 and L-SMASH Source, neither one reports the fpsNum/fpsDen as 0/0.

**Comment by sekrit-twc** [comment]
I used my own source filter for this purpose. Not sure if any actual filters in the wild use the 0/0 part of the API spec.
